[package]
name = "fnprint-emu"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Microexecution engine that records function behavior for fnprint"
repository.workspace = true

[dependencies]
unicorn-engine = { workspace = true }
capstone = { workspace = true }
fnprint-trace = { path = "../fnprint-trace", version = "0.2.5" }
fnprint-loader = { path = "../fnprint-loader", version = "0.2.5" }

[lints]
workspace = true
